#!/usr/bin/env bash
# Local e2e stack: bitcoind+LND (docker), CKB+Fiber (offckb), standalone CCH (fnn).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
DATA="$ROOT/data"
RUNTIME_ENV="$ROOT/runtime.env"
CCH_DIR="$DATA/cch"
CCH_PID="$CCH_DIR/fnn.pid"
CCH_LOG="$CCH_DIR/fnn.log"
CCH_RPC_URL="${CCH_RPC_URL:-http://127.0.0.1:8227}"
OPERATOR_RPC_URL="${OPERATOR_RPC_URL:-http://127.0.0.1:21714}"
USER_RPC_URL="${USER_RPC_URL:-http://127.0.0.1:21715}"
CKB_RPC_URL="${CKB_RPC_URL:-http://127.0.0.1:8114}"
CHANNEL_FUNDING_RAW="${CHANNEL_FUNDING_RAW:-100000000}"
E2E_AMOUNT_RAW="${E2E_AMOUNT_RAW:-50000}"
COMPOSE=(docker compose -f "$ROOT/docker-compose.yml" --project-directory "$ROOT")

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

compose() { "${COMPOSE[@]}" "$@"; }

btc() {
  compose exec -T bitcoind bitcoin-cli -regtest -rpcuser=btc -rpcpassword=btc "$@"
}

lncli_cch() {
  compose exec -T lnd-cch lncli --network=regtest "$@"
}

lncli_user() {
  compose exec -T lnd-user lncli --network=regtest "$@"
}

wait_for() {
  local name="$1" tries="${2:-60}" delay="${3:-2}"
  shift 3 || true
  local i=0
  until "$@"; do
    i=$((i + 1))
    if (( i >= tries )); then
      die "timed out waiting for $name"
    fi
    sleep "$delay"
  done
}

http_rpc_ok() {
  local url="$1" method="${2:-node_info}"
  python3 - "$url" "$method" <<'PY'
import json, sys, urllib.request, urllib.error
url, method = sys.argv[1], sys.argv[2]
req = urllib.request.Request(
    url,
    data=json.dumps({"id": 1, "jsonrpc": "2.0", "method": method, "params": []}).encode(),
    headers={"content-type": "application/json"},
)
try:
    urllib.request.urlopen(req, timeout=3)
except urllib.error.HTTPError:
    sys.exit(0)
except Exception:
    sys.exit(1)
PY
}

ensure_dirs() {
  mkdir -p "$DATA/bitcoind" "$DATA/lnd-cch" "$DATA/lnd-user" "$CCH_DIR/fiber"
}

ensure_fnn() {
  local bin="$CCH_DIR/bin/fnn"
  if [[ -x "$bin" ]]; then
    return
  fi
  need fiber-pay
  log "downloading Fiber fnn v0.9.0 into $CCH_DIR"
  fiber-pay --data-dir "$CCH_DIR" binary download --version v0.9.0
  [[ -x "$bin" ]] || die "fnn binary missing at $bin"
}

ensure_sk() {
  local sk="$CCH_DIR/fiber/sk"
  if [[ ! -s "$sk" ]]; then
    openssl rand 32 >"$sk"
    chmod 600 "$sk"
  fi
}

write_runtime_env() {
  local udt_file="$DATA/udt.json"
  cat >"$RUNTIME_ENV" <<EOF
# Generated by ops/stack.sh — do not commit
FNN_RPC_URL=$OPERATOR_RPC_URL
CCH_RPC_URL=$CCH_RPC_URL
CKB_RPC_URL=$CKB_RPC_URL
SKIP_CAPACITY_GIFT=1
CCH_BASE_FEE_SATS=100
CCH_FEE_RATE_PPM=3000
CORS_ORIGIN=http://localhost:5173
VITE_API_BASE_URL=http://localhost:3001/api
OPERATOR_CHANNEL_FUNDING_AMOUNT=$CHANNEL_FUNDING_RAW
EOF
  if [[ -f "$udt_file" ]]; then
    python3 - "$udt_file" "$RUNTIME_ENV" <<'PY'
import json, sys
udt = json.load(open(sys.argv[1]))
with open(sys.argv[2], "a") as fh:
    fh.write(f"LOCAL_UDT_CODE_HASH={udt['code_hash']}\n")
    fh.write(f"LOCAL_UDT_HASH_TYPE={udt['hash_type']}\n")
    fh.write(f"LOCAL_UDT_ARGS={udt['args']}\n")
PY
  fi
  log "wrote $RUNTIME_ENV"
}

sync_dotenv() {
  local env_file="$REPO/.env"
  if [[ -f "$env_file" ]]; then
    log "leaving existing $env_file in place (runtime copy is $RUNTIME_ENV)"
    return
  fi
  cp "$RUNTIME_ENV" "$env_file"
  log "created $env_file from runtime env"
}

# --- lightning -----------------------------------------------------------

up_lightning() {
  need docker
  docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker Desktop and retry."
  ensure_dirs
  log "starting bitcoind + lnd-cch + lnd-user"
  compose up -d

  log "waiting for bitcoind"
  wait_for bitcoind 60 2 bash -c 'docker compose -f "'"$ROOT"'/docker-compose.yml" --project-directory "'"$ROOT"'" exec -T bitcoind bitcoin-cli -regtest -rpcuser=btc -rpcpassword=btc getblockchaininfo >/dev/null'

  if ! btc getwalletinfo >/dev/null 2>&1; then
    log "creating bitcoind wallet"
    btc createwallet cch >/dev/null
  fi

  local blocks
  blocks="$(btc getblockcount)"
  if (( blocks < 101 )); then
    local addr
    addr="$(btc getnewaddress)"
    log "mining $((101 - blocks)) block(s) to $addr"
    btc generatetoaddress "$((101 - blocks))" "$addr" >/dev/null
  fi

  log "waiting for lnd-cch"
  wait_for lnd-cch 60 2 bash -c 'docker compose -f "'"$ROOT"'/docker-compose.yml" --project-directory "'"$ROOT"'" exec -T lnd-cch lncli --network=regtest getinfo >/dev/null'
  log "waiting for lnd-user"
  wait_for lnd-user 60 2 bash -c 'docker compose -f "'"$ROOT"'/docker-compose.yml" --project-directory "'"$ROOT"'" exec -T lnd-user lncli --network=regtest getinfo >/dev/null'

  fund_and_open_ln_channel
}

user_has_outbound() {
  lncli_user listchannels | python3 -c "import json,sys; chs=json.load(sys.stdin).get('channels') or []; sys.exit(0 if any(int(c.get('local_balance') or 0) >= 500000 and c.get('active') for c in chs) else 1)"
}

fund_and_open_ln_channel() {
  if user_has_outbound; then
    log "lightning channel already has user outbound liquidity"
    return
  fi

  local user_addr cch_pubkey
  user_addr="$(lncli_user newaddress p2tr | python3 -c 'import json,sys; print(json.load(sys.stdin)["address"])')"
  cch_pubkey="$(lncli_cch getinfo | python3 -c 'import json,sys; print(json.load(sys.stdin)["identity_pubkey"])')"
  log "funding user LND $user_addr (needs outbound to pay CCH invoices)"
  btc -named sendtoaddress address="$user_addr" amount=5 fee_rate=25 >/dev/null
  btc -generate 1 >/dev/null

  log "opening 1_000_000 sat channel user -> CCH ($cch_pubkey)"
  local tries=8
  until lncli_user openchannel --node_key "$cch_pubkey" --connect lnd-cch:9735 --local_amt 1000000 --sat_per_vbyte 1 --min_confs 0 >/dev/null; do
    tries=$((tries - 1))
    (( tries > 0 )) || die "failed to open lightning channel"
    sleep 3
  done
  btc -generate 6 >/dev/null
  wait_for "user outbound ln channel" 30 2 bash -c '
    docker compose -f "'"$ROOT"'/docker-compose.yml" --project-directory "'"$ROOT"'" exec -T lnd-user \
      lncli --network=regtest listchannels \
    | python3 -c "import json,sys; chs=json.load(sys.stdin).get(\"channels\") or []; sys.exit(0 if any(int(c.get(\"local_balance\") or 0) >= 500000 and c.get(\"active\") for c in chs) else 1)"
  '
  log "lightning channel active (user can pay CCH)"
}

down_lightning() {
  compose down --remove-orphans
}

# --- CKB / Fiber ---------------------------------------------------------

offckb_devnet_dir() {
  python3 - <<'PY'
import json, subprocess, re, os, pathlib
out = subprocess.check_output(["offckb", "config", "list"], text=True)
# config file path is printed first
for line in out.splitlines():
    if "configPath" in line or "devnet" in line and "offckb" in line:
        pass
m = re.search(r'"configPath":\s*"([^"]+)"', out)
if m:
    print(m.group(1))
    raise SystemExit(0)
# fallback
p = pathlib.Path.home() / "Library/Application Support/offckb-nodejs/devnet"
print(p)
PY
}

enable_fiber_pubsub() {
  local devnet nodes
  devnet="$(offckb_devnet_dir)"
  nodes="$devnet/fiber/nodes.yml"
  mkdir -p "$(dirname "$nodes")"
  cat >"$nodes" <<'EOF'
nodes:
  - id: 1
    config:
      rpc:
        enabled_modules:
          - channel
          - payment
          - graph
          - info
          - invoice
          - peer
          - watchtower
          - pubsub
  - id: 2
    config:
      rpc:
        enabled_modules:
          - channel
          - payment
          - graph
          - info
          - invoice
          - peer
          - watchtower
          - pubsub
EOF
  log "wrote Fiber RPC pubsub override $nodes"
}

up_ckb_fiber() {
  need offckb
  enable_fiber_pubsub
  if http_rpc_ok "$OPERATOR_RPC_URL" && http_rpc_ok "$USER_RPC_URL"; then
    local cfg
    cfg="$(offckb_devnet_dir)/fiber/nodes/1/config.yml"
    if [[ -f "$cfg" ]] && grep -q pubsub "$cfg"; then
      log "offckb fiber already running with pubsub"
    else
      log "restarting Fiber nodes to enable pubsub for CCH"
      offckb fiber stop >/dev/null 2>&1 || true
      offckb fiber start --nodes 2 --daemon \
        || die "offckb fiber start failed after enabling pubsub"
    fi
  elif http_rpc_ok "$CKB_RPC_URL" get_tip_header; then
    log "CKB is up; starting Fiber nodes (this may download FNN 0.9.0)"
    offckb fiber start --nodes 2 --daemon \
      || die "offckb fiber start failed. If this devnet predates Fiber genesis contracts, rebuild with: offckb node stop; offckb clean; then re-run ops/stack.sh up"
  else
    log "starting offckb CKB devnet + 2 Fiber nodes (this may download FNN 0.9.0)"
    offckb node --fiber --fiber-nodes 2 --daemon \
      || die "offckb node --fiber failed. If this devnet predates Fiber genesis contracts, rebuild with: offckb node stop; offckb clean; then re-run ops/stack.sh up"
  fi
  wait_for "ckb rpc" 90 2 http_rpc_ok "$CKB_RPC_URL" get_tip_header
  wait_for "operator fiber rpc" 90 2 http_rpc_ok "$OPERATOR_RPC_URL"
  wait_for "user fiber rpc" 90 2 http_rpc_ok "$USER_RPC_URL"
  log "CKB + Fiber nodes are up"
}

issue_udt() {
  local udt_file="$DATA/udt.json"
  if [[ -f "$udt_file" ]]; then
    log "reusing UDT script from $udt_file"
    return
  fi
  need offckb
  python3 - "$DATA" <<'PY'
import json, os, pathlib, shutil, subprocess, sys, time

data = pathlib.Path(sys.argv[1])
candidates = []
env = os.environ.get("OFFCKB_ACCOUNT_JSON")
if env:
    candidates.append(pathlib.Path(env))
cli = shutil.which("offckb")
if cli:
    cli_p = pathlib.Path(cli).resolve()
    for parent in cli_p.parents:
        acc = parent / "lib/node_modules/@offckb/cli/account/account.json"
        if acc.exists():
            candidates.append(acc)
            break
    candidates.append(pathlib.Path(cli).parent.parent / "lib/node_modules/@offckb/cli/account/account.json")

acc_path = next((c for c in candidates if c.exists()), None)
if acc_path is None:
    raise SystemExit("could not locate offckb account.json")
acc = json.loads(acc_path.read_text())
addr_op, addr_user, priv19 = acc[3]["address"], acc[4]["address"], acc[19]["privkey"]
keyfile = data / "udt-issuer.key"
keyfile.write_text(priv19 + "\n")
keyfile.chmod(0o600)

def issue(to, label):
    last = None
    for attempt in range(8):
        result = subprocess.run(
            ["offckb", "--json", "udt", "issue", "100000000000", "--udt-kind", "xudt",
             "--to", to, "--privkey-file", str(keyfile), "--network", "devnet"],
            capture_output=True, text=True,
        )
        (data / f"udt-issue-{label}.log").write_text(result.stdout + "\n" + result.stderr)
        if result.returncode == 0:
            return result.stdout
        last = result.stdout + result.stderr
        if "PoolRejectedRBF" in last or "PoolRejectedDuplicated" in last or "Rejected" in last:
            time.sleep(2 + attempt)
            continue
        raise SystemExit(f"offckb udt issue failed:\n{last}")
    raise SystemExit(f"offckb udt issue failed after retries:\n{last}")

print(f"issuing xUDT to operator {addr_op}", flush=True)
out = issue(addr_op, "operator")
time.sleep(2)
print(f"issuing xUDT to user {addr_user}", flush=True)
issue(addr_user, "user")

try:
    parsed = json.loads(out)
except json.JSONDecodeError as exc:
    raise SystemExit(f"could not parse issue JSON: {exc}\n{out[:2000]}")
args = parsed.get("typeArgs") or parsed.get("type_args") or parsed.get("args")
if not args:
    raise SystemExit(f"issue output missing typeArgs:\n{out[:2000]}")

scripts = subprocess.run(
    ["offckb", "system-scripts", "--network", "devnet", "--export-style", "ccc"],
    capture_output=True, text=True, check=True,
).stdout
start = scripts.find("{")
end = scripts.rfind("}")
if start < 0 or end < 0:
    raise SystemExit(f"could not parse system-scripts:\n{scripts[:2000]}")
known = json.loads(scripts[start:end + 1])
xudt = known.get("XUdt") or known.get("xudt")
if not xudt:
    raise SystemExit(f"system-scripts missing XUdt: {list(known)}")
udt = {
    "code_hash": xudt.get("codeHash") or xudt.get("code_hash"),
    "hash_type": str(xudt.get("hashType") or xudt.get("hash_type")).lower(),
    "args": args,
}
if not all(udt.values()):
    raise SystemExit(f"incomplete UDT script: {udt}")
(data / "udt.json").write_text(json.dumps(udt, indent=2) + "\n")
print(json.dumps(udt, indent=2))
PY
  log "UDT script saved to $udt_file"
}

open_fiber_channel() {
  local udt_file="$DATA/udt.json"
  [[ -f "$udt_file" ]] || die "missing $udt_file — issue UDT first"
  python3 - "$OPERATOR_RPC_URL" "$USER_RPC_URL" "$udt_file" "$CHANNEL_FUNDING_RAW" <<'PY'
import json, sys, time, urllib.request

op_url, user_url, udt_path, funding = sys.argv[1:5]
udt = json.load(open(udt_path))

def call(url, method, params, timeout=60):
    req = urllib.request.Request(
        url,
        data=json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode(),
        headers={"content-type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        payload = json.load(resp)
    if payload.get("error"):
        raise SystemExit(f"{method} error: {payload['error']}")
    return payload.get("result")

def list_channels(url, pending=False):
    params = [{"only_pending": True}] if pending else [{}]
    result = call(url, "list_channels", params) or {}
    if isinstance(result, dict):
        return result.get("channels") or []
    return result or []

def state_name(ch):
    state = ch.get("state") or {}
    if isinstance(state, dict):
        return state.get("state_name") or ""
    return str(state)

ready = [ch for ch in list_channels(user_url) if state_name(ch) == "ChannelReady"]
if ready:
    print(f"fiber UDT channel already ready {ready[0].get('channel_id')}")
    raise SystemExit(0)

user_info = call(user_url, "node_info", [])
user_pubkey = user_info.get("node_id") or user_info.get("pubkey")
addrs = user_info.get("addresses") or []
if addrs:
    try:
        call(op_url, "connect_peer", [{"address": addrs[0]}])
    except Exception as exc:
        print(f"connect_peer (best-effort): {exc}", file=sys.stderr)

opened = call(op_url, "open_channel", [{
    "pubkey": user_pubkey,
    "funding_amount": hex(int(funding)),
    "funding_udt_type_script": {
        "code_hash": udt["code_hash"],
        "hash_type": udt["hash_type"],
        "args": udt["args"],
    },
    "one_way": True,
    "public": False,
}])
print(f"open_channel -> {json.dumps(opened)}")

temp = None
for _ in range(30):
    for ch in list_channels(user_url, pending=True):
        if state_name(ch) == "NegotiatingFunding" or ch.get("is_acceptor"):
            temp = ch.get("channel_id")
            break
    if temp:
        break
    time.sleep(2)
if not temp:
    raise SystemExit("user node never saw a pending channel")

accepted = call(user_url, "accept_channel", [{
    "temporary_channel_id": temp,
    "funding_amount": "0x0",
}])
print(f"accept_channel -> {json.dumps(accepted)}")

for _ in range(90):
    for ch in list_channels(user_url):
        if state_name(ch) == "ChannelReady":
            print(f"CHANNEL_READY {ch.get('channel_id')}")
            raise SystemExit(0)
    time.sleep(2)
raise SystemExit("timed out waiting for CHANNEL_READY")
PY
}

# --- CCH -----------------------------------------------------------------

write_cch_config() {
  local udt_file="$DATA/udt.json"
  [[ -f "$udt_file" ]] || die "missing $udt_file"
  local cert="$DATA/lnd-cch/tls.cert"
  local macaroon="$DATA/lnd-cch/data/chain/bitcoin/regtest/admin.macaroon"
  [[ -f "$cert" ]] || die "missing LND TLS cert at $cert — start lightning first"
  [[ -f "$macaroon" ]] || die "missing LND macaroon at $macaroon — start lightning first"
  python3 - "$udt_file" "$cert" "$macaroon" "$CCH_DIR/config.yml" "$OPERATOR_RPC_URL" <<'PY'
import json, pathlib, sys
udt = json.load(open(sys.argv[1]))
cert, macaroon, dest, fiber_rpc = sys.argv[2], sys.argv[3], pathlib.Path(sys.argv[4]), sys.argv[5]
script_json = json.dumps({
    "code_hash": udt["code_hash"],
    "hash_type": udt["hash_type"],
    "args": udt["args"],
}, separators=(",", ":"))
dest.write_text(
    "rpc:\n"
    "  listening_addr: 127.0.0.1:8227\n"
    "  enabled_modules:\n"
    "    - cch\n"
    "\n"
    "cch:\n"
    "  lnd_rpc_url: https://127.0.0.1:10009\n"
    f"  lnd_cert_path: {cert}\n"
    f"  lnd_macaroon_path: {macaroon}\n"
    f"  wrapped_btc_type_script_args: \"{udt['args']}\"\n"
    f"  wrapped_btc_type_script: {json.dumps(script_json)}\n"
    f"  fiber_rpc_url: {fiber_rpc}\n"
    "  base_fee_sats: 100\n"
    "  fee_rate_per_million_sats: 3000\n"
    "\n"
    "services:\n"
    "  - rpc\n"
    "  - cch\n"
)
print(dest)
PY
}

cch_running() {
  [[ -f "$CCH_PID" ]] && kill -0 "$(cat "$CCH_PID")" 2>/dev/null
}

up_cch() {
  ensure_dirs
  ensure_fnn
  ensure_sk
  write_cch_config
  if cch_running; then
    log "CCH already running pid=$(cat "$CCH_PID")"
    return
  fi
  log "starting standalone CCH on $CCH_RPC_URL"
  nohup "$CCH_DIR/bin/fnn" -c "$CCH_DIR/config.yml" -d "$CCH_DIR" >"$CCH_LOG" 2>&1 &
  echo $! >"$CCH_PID"
  wait_for "CCH rpc" 40 1 http_rpc_ok "$CCH_RPC_URL" foo
  log "CCH is up"
}

down_cch() {
  if [[ -f "$CCH_PID" ]]; then
    local pid
    pid="$(cat "$CCH_PID")"
    if kill -0 "$pid" 2>/dev/null; then
      log "stopping CCH pid=$pid"
      kill "$pid" || true
      sleep 1
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$CCH_PID"
  fi
}

# --- commands ------------------------------------------------------------

cmd_up() {
  need python3
  need openssl
  need jq
  up_lightning
  up_ckb_fiber
  issue_udt
  open_fiber_channel
  up_cch
  write_runtime_env
  sync_dotenv
  cmd_status
  cat <<EOF

Local e2e stack is up.

  Bitcoin / LND     docker compose in ops/
  CKB               $CKB_RPC_URL   (offckb)
  Operator Fiber    $OPERATOR_RPC_URL
  User Fiber        $USER_RPC_URL
  CCH               $CCH_RPC_URL
  Env               $RUNTIME_ENV  (copied to .env if it did not exist)

Next:
  npm run stack:e2e          # CLI protocol test (invoice → pay BTC → UDT arrives)
  npm run dev                # API + web (web WASM is still testnet; see ops/README.md)
EOF
}

cmd_down() {
  down_cch
  if command -v offckb >/dev/null 2>&1; then
    log "stopping offckb node + fiber"
    offckb node stop --force >/dev/null 2>&1 || true
    offckb fiber stop >/dev/null 2>&1 || true
  fi
  if command -v docker >/dev/null 2>&1; then
    down_lightning || true
  fi
  log "stack stopped (chain/LND data kept in $DATA)"
}

cmd_status() {
  echo "--- lightning ---"
  if docker info >/dev/null 2>&1; then
    compose ps || true
    lncli_cch getinfo 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print('cch alias', d.get('alias'), 'synced', d.get('synced_to_chain'), 'channels', d.get('num_active_channels'))" || echo "lnd-cch not ready"
    lncli_user getinfo 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print('user alias', d.get('alias'), 'synced', d.get('synced_to_chain'), 'channels', d.get('num_active_channels'))" || echo "lnd-user not ready"
  else
    echo "docker not running"
  fi
  echo "--- ckb / fiber ---"
  if command -v offckb >/dev/null 2>&1; then
    offckb fiber status || true
  fi
  echo "--- cch ---"
  if cch_running; then
    echo "CCH pid=$(cat "$CCH_PID") rpc=$CCH_RPC_URL"
  else
    echo "CCH not running"
  fi
}

cmd_e2e() {
  [[ -f "$DATA/udt.json" ]] || die "stack is not up (missing $DATA/udt.json). Run: ops/stack.sh up"
  cch_running || die "CCH is not running. Run: ops/stack.sh up"
  python3 - "$USER_RPC_URL" "$CCH_RPC_URL" "$DATA/udt.json" "$E2E_AMOUNT_RAW" "$ROOT" <<'PY'
import json, secrets, subprocess, sys, time, urllib.request

user_url, cch_url, udt_path, amount, root = sys.argv[1:6]
udt = json.load(open(udt_path))

def call(url, method, params, timeout=90):
    req = urllib.request.Request(
        url,
        data=json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode(),
        headers={"content-type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        payload = json.load(resp)
    if payload.get("error"):
        raise SystemExit(f"{method} error: {json.dumps(payload['error'])}")
    return payload.get("result")

def lncli_user(*args):
    return subprocess.Popen(
        ["docker", "compose", "-f", f"{root}/docker-compose.yml",
         "--project-directory", root, "exec", "-T", "lnd-user",
         "lncli", "--network=regtest", *args],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
    )

preimage = "0x" + secrets.token_hex(32)
invoice = None
last_err = None
for currency in ("Fibd", "Fibt"):
    try:
        invoice = call(user_url, "new_invoice", [{
            "amount": hex(int(amount)),
            "currency": currency,
            "hash_algorithm": "sha256",
            "udt_type_script": {
                "code_hash": udt["code_hash"],
                "hash_type": udt["hash_type"],
                "args": udt["args"],
            },
            "payment_preimage": preimage,
        }])
        print(f"created invoice currency={currency}")
        break
    except SystemExit as exc:
        last_err = exc
if invoice is None:
    raise SystemExit(last_err or "new_invoice failed")

pay_req = invoice.get("invoice_address")
inv_obj = invoice.get("invoice") or {}
payment_hash = (inv_obj.get("data") or {}).get("payment_hash") or invoice.get("payment_hash")
print(f"fiber invoice: {str(pay_req)[:88]}...")
print(f"payment_hash: {payment_hash}")

order = call(cch_url, "receive_btc", [{"fiber_pay_req": pay_req}])
incoming = order.get("incoming_invoice")
bolt11 = incoming.get("Lightning") if isinstance(incoming, dict) else incoming
payment_hash = order.get("payment_hash") or payment_hash
print(f"bolt11: {str(bolt11)[:88]}...")
print(f"cch status: {order.get('status')} fee={order.get('fee_sats')}")

print("paying bolt11 from user LND (background)...")
pay = lncli_user("payinvoice", "--force", bolt11)

for _ in range(45):
    got = call(cch_url, "get_cch_order", [{"payment_hash": payment_hash}])
    status = got.get("status")
    print(f"  order status={status}")
    if status in ("Success", "OutgoingSuccess"):
        inv = call(user_url, "get_invoice", [{"payment_hash": payment_hash}])
        print(f"user invoice: {json.dumps(inv)[:800]}")
        print("E2E PASS")
        pay.terminate()
        raise SystemExit(0)
    if status in ("Failed", "Expired"):
        pay.terminate()
        raise SystemExit(f"E2E FAIL order status={status}")
    time.sleep(2)

if pay.poll() is not None:
    out, _ = pay.communicate()
    print(out[-1500:])
raise SystemExit("E2E FAIL: timed out waiting for CCH Success")
PY
}

usage() {
  cat <<EOF
Usage: ops/stack.sh <command>

  up        Start bitcoind+LND, offckb CKB/Fiber, CCH, fund channels
  down      Stop CCH, offckb, lightning (keeps data)
  status    Show process / channel status
  e2e       Run receive_btc protocol test (user Fiber invoice → user LND pays)
  lightning Start only the Bitcoin/LND docker stack
  logs      Tail CCH + compose logs

Requires: docker, offckb, fiber-pay, python3, jq, openssl
EOF
}

cmd="${1:-}"
case "$cmd" in
  up) cmd_up ;;
  down) cmd_down ;;
  status) cmd_status ;;
  e2e) cmd_e2e ;;
  lightning) up_lightning ;;
  logs)
    echo "--- cch ---"
    tail -n 80 "$CCH_LOG" 2>/dev/null || true
    echo "--- compose ---"
    compose logs --tail=40 || true
    ;;
  -h|--help|help|"") usage ;;
  *) usage; exit 1 ;;
esac
